
# Send a repo dispatch on pushes to the dunfell branch in order to trigger a build

name: repo_dispatch

on:
  push:
    branches: [ dunfell ]
#  pull_request:
#    branches: [ dunfell ]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: self-hosted
    steps:
      - name: Dispatch on push to dunfell
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/NetworkGradeLinux/mion-ci/dispatches' \
          --header 'authorization: Bearer ${{ secrets.ACCESS_TOKEN }}' \
          --data '{"event_type": "push", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
